#!/usr/bin/env python3
"""Embed five deterministic test images per Shapes2D class in firmware."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image

IMAGE_WIDTH = 96
IMAGE_HEIGHT = 96
CLASS_LABELS = ("circle", "square", "triangle")
# Keep the RAM-load firmware under the STM32N6 secure-RAM image limit.
IMAGES_PER_CLASS = 1
APP_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_HEADER = APP_ROOT / "src" / "embedded_self_test_images.h"


def format_bytes(name: str, payload: bytes) -> str:
    lines = [f"static const uint8_t {name}[] = {{"]
    for offset in range(0, len(payload), 12):
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in payload[offset : offset + 12]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("test_root", type=Path, help="Shapes2D test dataset root")
    args = parser.parse_args()

    selected: list[tuple[str, Path, bytes]] = []
    for label in CLASS_LABELS:
        files = sorted((args.test_root / label).glob("*.png"))[:IMAGES_PER_CLASS]
        if len(files) != IMAGES_PER_CLASS:
            raise SystemExit(f"Expected {IMAGES_PER_CLASS} images in {args.test_root / label}")
        for path in files:
            image = Image.open(path).convert("RGB").resize((IMAGE_WIDTH, IMAGE_HEIGHT))
            selected.append((label, path, image.tobytes()))

    lines = [
        "/* Generated by tools/generate_embedded_self_test_header.py. */",
        "#ifndef STM32N6_SHAPES_EMBEDDED_SELF_TEST_IMAGES_H_",
        "#define STM32N6_SHAPES_EMBEDDED_SELF_TEST_IMAGES_H_",
        "#include <stdint.h>",
        "typedef struct { const char *label; const char *name; const uint8_t *rgb_data; } embedded_self_test_case_t;",
        "",
    ]
    names = []
    for index, (_, _, payload) in enumerate(selected):
        name = f"embedded_self_test_image_{index}"
        names.append(name)
        lines.extend([format_bytes(name, payload), ""])
    lines.append("static const embedded_self_test_case_t embedded_self_test_cases[] = {")
    for index, (label, path, _) in enumerate(selected):
        lines.append(f'    {{ "{label}", "{path.stem}", {names[index]} }},')
    lines.extend([
        "};",
        "#define EMBEDDED_SELF_TEST_CASE_COUNT (sizeof(embedded_self_test_cases) / sizeof(embedded_self_test_cases[0]))",
        "#endif /* STM32N6_SHAPES_EMBEDDED_SELF_TEST_IMAGES_H_ */",
        "",
    ])
    OUTPUT_HEADER.write_text("\n".join(lines))
    print(f"Wrote {OUTPUT_HEADER} with {len(selected)} images")


if __name__ == "__main__":
    main()
